[versions]
decompose = "1.0.0"
nostrino = "0.0.4-SNAPSHOT"

[libraries]
decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }
nostrino = { module = "app.cash.nostrino:nostr-sdk", version.ref = "nostrino" }

[plugins]
